# Etapa de construcción

FROM maven:3.9-amazoncorretto-21 AS build
WORKDIR /app

# Copiamos el proyecto completo

COPY pom.xml .
COPY src ./src

# Empaquetamos la aplicación

RUN mvn package -DskipTests

# Etapa de ejecución

FROM amazoncorretto:21-alpine

# Argumentos para configurar la conexión a la base de datos

ENV QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/db_customer \
QUARKUS_DATASOURCE_USERNAME=admin \
QUARKUS_DATASOURCE_PASSWORD=admin

WORKDIR /app

# Copiamos todo el directorio quarkus-app

COPY --from=build /app/target/quarkus-app/ /app/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "quarkus-run.jar"]
